### ISSUE TITLE
Add ability to filter calls based on caller number

### ISSUE THREAD

**Issue by nvinayvarma189** [skit-ai/skit-calls#3]
Sometimes multiple people (SPMs, MLSEs, SEs, etc) will be making calls to the bot for internal testing purposes. The OPS team members will also be making calls to the same flow. 

Currently, we do not have a way to filter the calls made by specific people, It is almost always the case that OPS team members will be calling from the same set of phone numbers. So we can use the caller number for filtering purposes (this feature is already available in the call reporting interface of the console.)

**Comment by ltbringer** [comment]
Doesn't this flag help? https://github.com/skit-ai/skit-calls/blob/5172d89a941ec6fd97f20ac32dcce95f13af0a8b/skit_calls/cli.py#L116

**Comment by nvinayvarma189** [comment]
yes, this should help. This issue is also outdated. I'm closing it
